version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - run:
          name: bundle install with no cache
          command: |
            bundle install
      - run:
          name: only run rspec
          command: |
            bundle exec rspec

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.7", "3.0", "3.1", "3.2"]
